export const API_URL = 'https://hemp-temps-api.uc.r.appspot.com'
// export const API_URL = 'http://localhost:4040'

export const countries = [
  // { name: 'Afghanistan', code: 'AF', region: 'Asia', flag: '🇦🇫' },
  // { name: 'Åland Islands', code: 'AX', region: 'Europe', flag: '🇦🇽' },
  // { name: 'Albania', code: 'AL', region: 'Europe', flag: '🇦🇱' },
  // { name: 'Algeria', code: 'DZ', region: 'Africa', flag: '🇩🇿' },
  // { name: 'American Samoa', code: 'AS', region: 'Oceania', flag: '🇦🇸' },
  // { name: 'Andorra', code: 'AD', region: 'Europe', flag: '🇦🇩' },
  // { name: 'Angola', code: 'AO', region: 'Africa', flag: '🇦🇴' },
  // { name: 'Anguilla', code: 'AI', region: 'Americas', flag: '🇦🇮' },
  // { name: 'Antarctica', code: 'AQ', region: 'Antarctic', flag: '🇦🇶' },
  // { name: 'Antigua and Barbuda', code: 'AG', region: 'Americas', flag: '🇦🇬' },
  // { name: 'Argentina', code: 'AR', region: 'Americas', flag: '🇦🇷' },
  // { name: 'Armenia', code: 'AM', region: 'Asia', flag: '🇦🇲' },
  // { name: 'Aruba', code: 'AW', region: 'Americas', flag: '🇦🇼' },
  // { name: 'Australia', code: 'AU', region: 'Oceania', flag: '🇦🇺' },
  // { name: 'Austria', code: 'AT', region: 'Europe', flag: '🇦🇹' },
  // { name: 'Azerbaijan', code: 'AZ', region: 'Asia', flag: '🇦🇿' },
  // { name: 'Bahamas', code: 'BS', region: 'Americas', flag: '🇧🇸' },
  // { name: 'Bahrain', code: 'BH', region: 'Asia', flag: '🇧🇭' },
  // { name: 'Bangladesh', code: 'BD', region: 'Asia', flag: '🇧🇩' },
  // { name: 'Barbados', code: 'BB', region: 'Americas', flag: '🇧🇧' },
  // { name: 'Belarus', code: 'BY', region: 'Europe', flag: '🇧🇾' },
  // { name: 'Belgium', code: 'BE', region: 'Europe', flag: '🇧🇪' },
  // { name: 'Belize', code: 'BZ', region: 'Americas', flag: '🇧🇿' },
  // { name: 'Benin', code: 'BJ', region: 'Africa', flag: '🇧🇯' },
  // { name: 'Bermuda', code: 'BM', region: 'Americas', flag: '🇧🇲' },
  // { name: 'Bolivia', code: 'BO', region: 'Americas', flag: '🇧🇴' },
  // { name: 'Bosnia and Herzegovina', code: 'BA', region: 'Europe', flag: '🇧🇦' },
  // { name: 'Botswana', code: 'BW', region: 'Africa', flag: '🇧🇼' },
  // { name: 'Bouvet Island', code: 'BV', region: 'Antarctic', flag: '🇧🇻' },
  // { name: 'Brazil', code: 'BR', region: 'Americas', flag: '🇧🇷' },
  // { name: 'British Indian Ocean Territory', code: 'IO', region: 'Africa', flag: '🇮🇴' },
  // { name: 'British Virgin Islands', code: 'VG', region: 'Americas', flag: '🇻🇬' },
  // { name: 'Bhutan', code: 'BT', region: 'Asia', flag: '🇧🇹' },
  // { name: 'Brunei', code: 'BN', region: 'Asia', flag: '🇧🇳' },
  // { name: 'Bulgaria', code: 'BG', region: 'Europe', flag: '🇧🇬' },
  // { name: 'Burkina Faso', code: 'BF', region: 'Africa', flag: '🇧🇫' },
  // { name: 'Burundi', code: 'BI', region: 'Africa', flag: '🇧🇮' },
  // { name: 'Cambodia', code: 'KH', region: 'Asia', flag: '🇰🇭' },
  // { name: 'Cameroon', code: 'CM', region: 'Africa', flag: '🇨🇲' },
  { name: 'Canada', code: 'CA', region: 'Americas', flag: '🇨🇦' },
  // { name: 'Cape Verde', code: 'CV', region: 'Africa', flag: '🇨🇻' },
  // { name: 'Caribbean Netherlands', code: 'BQ', region: 'Americas', flag: '🇧🇶' },
  // { name: 'Cayman Islands', code: 'KY', region: 'Americas', flag: '🇰🇾' },
  // { name: 'Central African Republic', code: 'CF', region: 'Africa', flag: '🇨🇫' },
  // { name: 'Chad', code: 'TD', region: 'Africa', flag: '🇹🇩' },
  // { name: 'Chile', code: 'CL', region: 'Americas', flag: '🇨🇱' },
  // { name: 'China', code: 'CN', region: 'Asia', flag: '🇨🇳' },
  // { name: 'Christmas Island', code: 'CX', region: 'Oceania', flag: '🇨🇽' },
  // { name: 'Cocos (Keeling) Islands', code: 'CC', region: 'Oceania', flag: '🇨🇨' },
  // { name: 'Colombia', code: 'CO', region: 'Americas', flag: '🇨🇴' },
  // { name: 'Comoros', code: 'KM', region: 'Africa', flag: '🇰🇲' },
  // { name: 'Cook Islands', code: 'CK', region: 'Oceania', flag: '🇨🇰' },
  // { name: 'Costa Rica', code: 'CR', region: 'Americas', flag: '🇨🇷' },
  // { name: 'Croatia', code: 'HR', region: 'Europe', flag: '🇭🇷' },
  // { name: 'Cuba', code: 'CU', region: 'Americas', flag: '🇨🇺' },
  // { name: 'Curaçao', code: 'CW', region: 'Americas', flag: '🇨🇼' },
  // { name: 'Cyprus', code: 'CY', region: 'Europe', flag: '🇨🇾' },
  // { name: 'Czechia', code: 'CZ', region: 'Europe', flag: '🇨🇿' },
  // { name: 'Denmark', code: 'DK', region: 'Europe', flag: '🇩🇰' },
  // { name: 'Djibouti', code: 'DJ', region: 'Africa', flag: '🇩🇯' },
  // { name: 'Dominica', code: 'DM', region: 'Americas', flag: '🇩🇲' },
  // { name: 'Dominican Republic', code: 'DO', region: 'Americas', flag: '🇩🇴' },
  // { name: 'DR Congo', code: 'CD', region: 'Africa', flag: '🇨🇩' },
  // { name: 'Ecuador', code: 'EC', region: 'Americas', flag: '🇪🇨' },
  // { name: 'Egypt', code: 'EG', region: 'Africa', flag: '🇪🇬' },
  // { name: 'El Salvador', code: 'SV', region: 'Americas', flag: '🇸🇻' },
  // { name: 'Equatorial Guinea', code: 'GQ', region: 'Africa', flag: '🇬🇶' },
  // { name: 'Eritrea', code: 'ER', region: 'Africa', flag: '🇪🇷' },
  // { name: 'Estonia', code: 'EE', region: 'Europe', flag: '🇪🇪' },
  // { name: 'Eswatini', code: 'SZ', region: 'Africa', flag: '🇸🇿' },
  // { name: 'Ethiopia', code: 'ET', region: 'Africa', flag: '🇪🇹' },
  // { name: 'Falkland Islands', code: 'FK', region: 'Americas', flag: '🇫🇰' },
  // { name: 'Faroe Islands', code: 'FO', region: 'Europe', flag: '🇫🇴' },
  // { name: 'Fiji', code: 'FJ', region: 'Oceania', flag: '🇫🇯' },
  // { name: 'Finland', code: 'FI', region: 'Europe', flag: '🇫🇮' },
  // { name: 'France', code: 'FR', region: 'Europe', flag: '🇫🇷' },
  // { name: 'French Guiana', code: 'GF', region: 'Americas', flag: '🇬🇫' },
  // { name: 'French Polynesia', code: 'PF', region: 'Oceania', flag: '🇵🇫' },
  // { name: 'French Southern and Antarctic Lands', code: 'TF', region: 'Antarctic', flag: '🇹🇫' },
  // { name: 'Gabon', code: 'GA', region: 'Africa', flag: '🇬🇦' },
  // { name: 'Gambia', code: 'GM', region: 'Africa', flag: '🇬🇲' },
  // { name: 'Georgia', code: 'GE', region: 'Asia', flag: '🇬🇪' },
  // { name: 'Germany', code: 'DE', region: 'Europe', flag: '🇩🇪' },
  // { name: 'Ghana', code: 'GH', region: 'Africa', flag: '🇬🇭' },
  // { name: 'Gibraltar', code: 'GI', region: 'Europe', flag: '🇬🇮' },
  // { name: 'Greece', code: 'GR', region: 'Europe', flag: '🇬🇷' },
  // { name: 'Greenland', code: 'GL', region: 'Americas', flag: '🇬🇱' },
  // { name: 'Grenada', code: 'GD', region: 'Americas', flag: '🇬🇩' },
  // { name: 'Guadeloupe', code: 'GP', region: 'Americas', flag: '🇬🇵' },
  // { name: 'Guam', code: 'GU', region: 'Oceania', flag: '🇬🇺' },
  // { name: 'Guatemala', code: 'GT', region: 'Americas', flag: '🇬🇹' },
  // { name: 'Guernsey', code: 'GG', region: 'Europe', flag: '🇬🇬' },
  // { name: 'Guinea', code: 'GN', region: 'Africa', flag: '🇬🇳' },
  // { name: 'Guinea-Bissau', code: 'GW', region: 'Africa', flag: '🇬🇼' },
  // { name: 'Guyana', code: 'GY', region: 'Americas', flag: '🇬🇾' },
  // { name: 'Haiti', code: 'HT', region: 'Americas', flag: '🇭🇹' },
  // { name: 'Heard Island and McDonald Islands', code: 'HM', region: 'Antarctic', flag: '🇭🇲' },
  // { name: 'Honduras', code: 'HN', region: 'Americas', flag: '🇭🇳' },
  // { name: 'Hong Kong', code: 'HK', region: 'Asia', flag: '🇭🇰' },
  // { name: 'Hungary', code: 'HU', region: 'Europe', flag: '🇭🇺' },
  // { name: 'Iceland', code: 'IS', region: 'Europe', flag: '🇮🇸' },
  // { name: 'India', code: 'IN', region: 'Asia', flag: '🇮🇳' },
  // { name: 'Indonesia', code: 'ID', region: 'Asia', flag: '🇮🇩' },
  // { name: 'Iran', code: 'IR', region: 'Asia', flag: '🇮🇷' },
  // { name: 'Iraq', code: 'IQ', region: 'Asia', flag: '🇮🇶' },
  // { name: 'Ireland', code: 'IE', region: 'Europe', flag: '🇮🇪' },
  // { name: 'Isle of Man', code: 'IM', region: 'Europe', flag: '🇮🇲' },
  // { name: 'Italy', code: 'IT', region: 'Europe', flag: '🇮🇹' },
  // { name: 'Ivory Coast', code: 'CI', region: 'Africa', flag: '🇨🇮' },
  // { name: 'Israel', code: 'IL', region: 'Asia', flag: '🇮🇱' },
  // { name: 'Japan', code: 'JP', region: 'Asia', flag: '🇯🇵' },
  // { name: 'Jamaica', code: 'JM', region: 'Americas', flag: '🇯🇲' },
  // { name: 'Jersey', code: 'JE', region: 'Europe', flag: '🇯🇪' },
  // { name: 'Jordan', code: 'JO', region: 'Asia', flag: '🇯🇴' },
  // { name: 'Kazakhstan', code: 'KZ', region: 'Asia', flag: '🇰🇿' },
  // { name: 'Kenya', code: 'KE', region: 'Africa', flag: '🇰🇪' },
  // { name: 'Kiribati', code: 'KI', region: 'Oceania', flag: '🇰🇮' },
  // { name: 'Kosovo', code: 'XK', region: 'Europe', flag: '🇽🇰' },
  // { name: 'Kuwait', code: 'KW', region: 'Asia', flag: '🇰🇼' },
  // { name: 'Kyrgyzstan', code: 'KG', region: 'Asia', flag: '🇰🇬' },
  // { name: 'Laos', code: 'LA', region: 'Asia', flag: '🇱🇦' },
  // { name: 'Latvia', code: 'LV', region: 'Europe', flag: '🇱🇻' },
  // { name: 'Lebanon', code: 'LB', region: 'Asia', flag: '🇱🇧' },
  // { name: 'Lesotho', code: 'LS', region: 'Africa', flag: '🇱🇸' },
  // { name: 'Liberia', code: 'LR', region: 'Africa', flag: '🇱🇷' },
  // { name: 'Libya', code: 'LY', region: 'Africa', flag: '🇱🇾' },
  // { name: 'Liechtenstein', code: 'LI', region: 'Europe', flag: '🇱🇮' },
  // { name: 'Lithuania', code: 'LT', region: 'Europe', flag: '🇱🇹' },
  // { name: 'Luxembourg', code: 'LU', region: 'Europe', flag: '🇱🇺' },
  // { name: 'Macau', code: 'MO', region: 'Asia', flag: '🇲🇴' },
  // { name: 'Madagascar', code: 'MG', region: 'Africa', flag: '🇲🇬' },
  // { name: 'Malawi', code: 'MW', region: 'Africa', flag: '🇲🇼' },
  // { name: 'Malaysia', code: 'MY', region: 'Asia', flag: '🇲🇾' },
  // { name: 'Maldives', code: 'MV', region: 'Asia', flag: '🇲🇻' },
  // { name: 'Mali', code: 'ML', region: 'Africa', flag: '🇲🇱' },
  // { name: 'Malta', code: 'MT', region: 'Europe', flag: '🇲🇹' },
  // { name: 'Marshall Islands', code: 'MH', region: 'Oceania', flag: '🇲🇭' },
  // { name: 'Martinique', code: 'MQ', region: 'Americas', flag: '🇲🇶' },
  // { name: 'Mauritania', code: 'MR', region: 'Africa', flag: '🇲🇷' },
  // { name: 'Mauritius', code: 'MU', region: 'Africa', flag: '🇲🇺' },
  // { name: 'Mayotte', code: 'YT', region: 'Africa', flag: '🇾🇹' },
  // { name: 'Mexico', code: 'MX', region: 'Americas', flag: '🇲🇽' },
  // { name: 'Micronesia', code: 'FM', region: 'Oceania', flag: '🇫🇲' },
  // { name: 'Moldova', code: 'MD', region: 'Europe', flag: '🇲🇩' },
  // { name: 'Mongolia', code: 'MN', region: 'Asia', flag: '🇲🇳' },
  // { name: 'Monaco', code: 'MC', region: 'Europe', flag: '🇲🇨' },
  // { name: 'Montenegro', code: 'ME', region: 'Europe', flag: '🇲🇪' },
  // { name: 'Montserrat', code: 'MS', region: 'Americas', flag: '🇲🇸' },
  // { name: 'Morocco', code: 'MA', region: 'Africa', flag: '🇲🇦' },
  // { name: 'Mozambique', code: 'MZ', region: 'Africa', flag: '🇲🇿' },
  // { name: 'Myanmar', code: 'MM', region: 'Asia', flag: '🇲🇲' },
  // { name: 'Namibia', code: 'NA', region: 'Africa', flag: '🇳🇦' },
  // { name: 'Nauru', code: 'NR', region: 'Oceania', flag: '🇳🇷' },
  // { name: 'Nepal', code: 'NP', region: 'Asia', flag: '🇳🇵' },
  // { name: 'Netherlands', code: 'NL', region: 'Europe', flag: '🇳🇱' },
  // { name: 'New Caledonia', code: 'NC', region: 'Oceania', flag: '🇳🇨' },
  // { name: 'New Zealand', code: 'NZ', region: 'Oceania', flag: '🇳🇿' },
  // { name: 'Nicaragua', code: 'NI', region: 'Americas', flag: '🇳🇮' },
  // { name: 'Niger', code: 'NE', region: 'Africa', flag: '🇳🇪' },
  // { name: 'Nigeria', code: 'NG', region: 'Africa', flag: '🇳🇬' },
  // { name: 'Niue', code: 'NU', region: 'Oceania', flag: '🇳🇺' },
  // { name: 'Norfolk Island', code: 'NF', region: 'Oceania', flag: '🇳🇫' },
  // { name: 'North Korea', code: 'KP', region: 'Asia', flag: '🇰🇵' },
  // { name: 'North Macedonia', code: 'MK', region: 'Europe', flag: '🇲🇰' },
  // { name: 'Northern Mariana Islands', code: 'MP', region: 'Oceania', flag: '🇲🇵' },
  // { name: 'Norway', code: 'NO', region: 'Europe', flag: '🇳🇴' },
  // { name: 'Oman', code: 'OM', region: 'Asia', flag: '🇴🇲' },
  // { name: 'Pakistan', code: 'PK', region: 'Asia', flag: '🇵🇰' },
  // { name: 'Palau', code: 'PW', region: 'Oceania', flag: '🇵🇼' },
  // { name: 'Palestine', code: 'PS', region: 'Asia', flag: '🇵🇸' },
  // { name: 'Panama', code: 'PA', region: 'Americas', flag: '🇵🇦' },
  // { name: 'Papua New Guinea', code: 'PG', region: 'Oceania', flag: '🇵🇬' },
  // { name: 'Paraguay', code: 'PY', region: 'Americas', flag: '🇵🇾' },
  // { name: 'Peru', code: 'PE', region: 'Americas', flag: '🇵🇪' },
  // { name: 'Philippines', code: 'PH', region: 'Asia', flag: '🇵🇭' },
  // { name: 'Pitcairn Islands', code: 'PN', region: 'Oceania', flag: '🇵🇳' },
  // { name: 'Poland', code: 'PL', region: 'Europe', flag: '🇵🇱' },
  // { name: 'Portugal', code: 'PT', region: 'Europe', flag: '🇵🇹' },
  // { name: 'Puerto Rico', code: 'PR', region: 'Americas', flag: '🇵🇷' },
  // { name: 'Qatar', code: 'QA', region: 'Asia', flag: '🇶🇦' },
  // { name: 'Republic of the Congo', code: 'CG', region: 'Africa', flag: '🇨🇬' },
  // { name: 'Réunion', code: 'RE', region: 'Africa', flag: '🇷🇪' },
  // { name: 'Romania', code: 'RO', region: 'Europe', flag: '🇷🇴' },
  // { name: 'Russia', code: 'RU', region: 'Europe', flag: '🇷🇺' },
  // { name: 'Rwanda', code: 'RW', region: 'Africa', flag: '🇷🇼' },
  // { name: 'Saint Barthélemy', code: 'BL', region: 'Americas', flag: '🇧🇱' },
  // { name: 'Saint Helena, Ascension and Tristan da Cunha', code: 'SH', region: 'Africa', flag: '🇸🇭' },
  // { name: 'Saint Kitts and Nevis', code: 'KN', region: 'Americas', flag: '🇰🇳' },
  // { name: 'Saint Lucia', code: 'LC', region: 'Americas', flag: '🇱🇨' },
  // { name: 'Saint Maarten', code: 'SX', region: 'Americas', flag: '🇸🇽' },
  // { name: 'Saint Martin', code: 'MF', region: 'Americas', flag: '🇲🇫' },
  // { name: 'Saint Pierre and Miquelon', code: 'PM', region: 'Americas', flag: '🇵🇲' },
  // { name: 'Saint Vincent and the Grenadines', code: 'VC', region: 'Americas', flag: '🇻🇨' },
  // { name: 'Samoa', code: 'WS', region: 'Oceania', flag: '🇼🇸' },
  // { name: 'San Marino', code: 'SM', region: 'Europe', flag: '🇸🇲' },
  // { name: 'São Tomé and Príncipe', code: 'ST', region: 'Africa', flag: '🇸🇹' },
  // { name: 'Saudi Arabia', code: 'SA', region: 'Asia', flag: '🇸🇦' },
  // { name: 'Senegal', code: 'SN', region: 'Africa', flag: '🇸🇳' },
  // { name: 'Serbia', code: 'RS', region: 'Europe', flag: '🇷🇸' },
  // { name: 'Seychelles', code: 'SC', region: 'Africa', flag: '🇸🇨' },
  // { name: 'Sierra Leone', code: 'SL', region: 'Africa', flag: '🇸🇱' },
  // { name: 'Singapore', code: 'SG', region: 'Asia', flag: '🇸🇬' },
  // { name: 'Slovakia', code: 'SK', region: 'Europe', flag: '🇸🇰' },
  // { name: 'Slovenia', code: 'SI', region: 'Europe', flag: '🇸🇮' },
  // { name: 'Solomon Islands', code: 'SB', region: 'Oceania', flag: '🇸🇧' },
  // { name: 'Somalia', code: 'SO', region: 'Africa', flag: '🇸🇴' },
  // { name: 'South Africa', code: 'ZA', region: 'Africa', flag: '🇿🇦' },
  // { name: 'South Georgia', code: 'GS', region: 'Antarctic', flag: '🇬🇸' },
  // { name: 'South Korea', code: 'KR', region: 'Asia', flag: '🇰🇷' },
  // { name: 'South Sudan', code: 'SS', region: 'Africa', flag: '🇸🇸' },
  // { name: 'Spain', code: 'ES', region: 'Europe', flag: '🇪🇸' },
  // { name: 'Sri Lanka', code: 'LK', region: 'Asia', flag: '🇱🇰' },
  // { name: 'Sudan', code: 'SD', region: 'Africa', flag: '🇸🇩' },
  // { name: 'Suriname', code: 'SR', region: 'Americas', flag: '🇸🇷' },
  // { name: 'Svalbard and Jan Mayen', code: 'SJ', region: 'Europe', flag: '🇸🇯' },
  // { name: 'Sweden', code: 'SE', region: 'Europe', flag: '🇸🇪' },
  // { name: 'Switzerland', code: 'CH', region: 'Europe', flag: '🇨🇭' },
  // { name: 'Syria', code: 'SY', region: 'Asia', flag: '🇸🇾' },
  // { name: 'Taiwan', code: 'TW', region: 'Asia', flag: '🇹🇼' },
  // { name: 'Tajikistan', code: 'TJ', region: 'Asia', flag: '🇹🇯' },
  // { name: 'Tanzania', code: 'TZ', region: 'Africa', flag: '🇹🇿' },
  // { name: 'Thailand', code: 'TH', region: 'Asia', flag: '🇹🇭' },
  // { name: 'Timor-Leste', code: 'TL', region: 'Asia', flag: '🇹🇱' },
  // { name: 'Togo', code: 'TG', region: 'Africa', flag: '🇹🇬' },
  // { name: 'Tokelau', code: 'TK', region: 'Oceania', flag: '🇹🇰' },
  // { name: 'Tonga', code: 'TO', region: 'Oceania', flag: '🇹🇴' },
  // { name: 'Trinidad and Tobago', code: 'TT', region: 'Americas', flag: '🇹🇹' },
  // { name: 'Tunisia', code: 'TN', region: 'Africa', flag: '🇹🇳' },
  // { name: 'Turkey', code: 'TR', region: 'Asia', flag: '🇹🇷' },
  // { name: 'Turkmenistan', code: 'TM', region: 'Asia', flag: '🇹🇲' },
  // { name: 'Turks and Caicos Islands', code: 'TC', region: 'Americas', flag: '🇹🇨' },
  // { name: 'Tuvalu', code: 'TV', region: 'Oceania', flag: '🇹🇻' },
  // { name: 'Uganda', code: 'UG', region: 'Africa', flag: '🇺🇬' },
  // { name: 'Ukraine', code: 'UA', region: 'Europe', flag: '🇺🇦' },
  // { name: 'United Arab Emirates', code: 'AE', region: 'Asia', flag: '🇦🇪' },
  // { name: 'United Kingdom', code: 'GB', region: 'Europe', flag: '🇬🇧' },
  { name: 'United States', code: 'US', region: 'Americas', flag: '🇺🇸' },
  // { name: 'United States Minor Outlying Islands', code: 'UM', region: 'Americas', flag: '🇺🇲' },
  // { name: 'United States Virgin Islands', code: 'VI', region: 'Americas', flag: '🇻🇮' },
  // { name: 'Uruguay', code: 'UY', region: 'Americas', flag: '🇺🇾' },
  // { name: 'Uzbekistan', code: 'UZ', region: 'Asia', flag: '🇺🇿' },
  // { name: 'Vanuatu', code: 'VU', region: 'Oceania', flag: '🇻🇺' },
  // { name: 'Vatican City', code: 'VA', region: 'Europe', flag: '🇻🇦' },
  // { name: 'Venezuela', code: 'VE', region: 'Americas', flag: '🇻🇪' },
  // { name: 'Vietnam', code: 'VN', region: 'Asia', flag: '🇻🇳' },
  // { name: 'Wallis and Futuna', code: 'WF', region: 'Oceania', flag: '🇼🇫' },
  // { name: 'Western Sahara', code: 'EH', region: 'Africa', flag: '🇪🇭' },
  // { name: 'Yemen', code: 'YE', region: 'Asia', flag: '🇾🇪' },
  // { name: 'Zambia', code: 'ZM', region: 'Africa', flag: '🇿🇲' },
  // { name: 'Zimbabwe', code: 'ZW', region: 'Africa', flag: '🇿🇼' },
]

export const states = [
  { name: 'Alabama', code: 'AL' },
  { name: 'Alaska', code: 'AK' },
  { name: 'Arizona', code: 'AZ' },
  { name: 'Arkansas', code: 'AR' },
  { name: 'California', code: 'CA' },
  { name: 'Colorado', code: 'CO' },
  { name: 'Connecticut', code: 'CT' },
  { name: 'Delaware', code: 'DE' },
  { name: 'Florida', code: 'FL' },
  { name: 'Georgia', code: 'GA' },
  { name: 'Hawaii', code: 'HI' },
  { name: 'Idaho', code: 'ID' },
  { name: 'Illinois', code: 'IL' },
  { name: 'Indiana', code: 'IN' },
  { name: 'Iowa', code: 'IA' },
  { name: 'Kansas', code: 'KS' },
  { name: 'Kentucky', code: 'KY' },
  { name: 'Louisiana', code: 'LA' },
  { name: 'Maine', code: 'ME' },
  { name: 'Maryland', code: 'MD' },
  { name: 'Massachusetts', code: 'MA' },
  { name: 'Michigan', code: 'MI' },
  { name: 'Minnesota', code: 'MN' },
  { name: 'Mississippi', code: 'MS' },
  { name: 'Missouri', code: 'MO' },
  { name: 'Montana', code: 'MT' },
  { name: 'Nebraska', code: 'NE' },
  { name: 'Nevada', code: 'NV' },
  { name: 'New Hampshire', code: 'NH' },
  { name: 'New Jersey', code: 'NJ' },
  { name: 'New Mexico', code: 'NM' },
  { name: 'New York', code: 'NY' },
  { name: 'North Carolina', code: 'NC' },
  { name: 'North Dakota', code: 'ND' },
  { name: 'Ohio', code: 'OH' },
  { name: 'Oklahoma', code: 'OK' },
  { name: 'Oregon', code: 'OR' },
  { name: 'Pennsylvania', code: 'PA' },
  { name: 'Rhode Island', code: 'RI' },
  { name: 'South Carolina', code: 'SC' },
  { name: 'South Dakota', code: 'SD' },
  { name: 'Tennessee', code: 'TN' },
  { name: 'Texas', code: 'TX' },
  { name: 'Utah', code: 'UT' },
  { name: 'Vermont', code: 'VT' },
  { name: 'Virginia', code: 'VA' },
  { name: 'Washington', code: 'WA' },
  { name: 'West Virginia', code: 'WV' },
  { name: 'Wisconsin', code: 'WI' },
  { name: 'Wyoming', code: 'WY' },
]

export const months = [
  { name: 'January', code: 'Jan.' },
  { name: 'February', code: 'Feb.' },
  { name: 'March', code: 'Mar.' },
  { name: 'April', code: 'Apr.' },
  { name: 'May', code: 'May' },
  { name: 'June', code: 'Jun.' },
  { name: 'July', code: 'Jul.' },
  { name: 'August', code: 'Aug.' },
  { name: 'September', code: 'Sep.' },
  { name: 'October', code: 'Oct.' },
  { name: 'November', code: 'Nov.' },
  { name: 'December', code: 'Dec.' },
]
export const days = [
  { name: '01', code: 'one' },
  { name: '02', code: 'two' },
  { name: '03', code: 'three' },
  { name: '04', code: 'four' },
  { name: '05', code: 'five' },
  { name: '06', code: 'six' },
  { name: '07', code: 'seven' },
  { name: '08', code: 'eight' },
  { name: '09', code: 'nine' },
  { name: '10', code: 'ten' },
  { name: '11', code: 'eleven' },
  { name: '12', code: 'twelve' },
  { name: '13', code: 'thirteen' },
  { name: '14', code: 'fourteen' },
  { name: '15', code: 'fifteen' },
  { name: '16', code: 'sixteen' },
  { name: '17', code: 'seventeen' },
  { name: '18', code: 'eighteen' },
  { name: '19', code: 'nineteen' },
  { name: '20', code: 'twenty' },
  { name: '21', code: 'twenty-one' },
  { name: '22', code: 'twenty-two' },
  { name: '23', code: 'twenty-three' },
  { name: '24', code: 'twenty-four' },
  { name: '25', code: 'twenty-five' },
  { name: '26', code: 'twenty-six' },
  { name: '27', code: 'twenty-seven' },
  { name: '28', code: 'twenty-eight' },
  { name: '29', code: 'twenty-nine' },
  { name: '30', code: 'thirty' },
  { name: '31', code: 'thirty-one' },
]

export const years = Array.from({ length: 116 }, (_, index) => {
  const currentYear = new Date().getFullYear()
  const year = currentYear - 16 - index
  return { name: year.toString(), code: year.toString() }
})

export const accountTypes = [
  { name: 'Checking', code: 'Checking' },
  { name: 'Savings', code: 'Savings' },
];