/**
 * AssetImage Component
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-images.cjs
 */

import React from 'react';
import { ImageMap } from './images.generated';
import { AssetImageProps } from './AssetImage.types';

/**
 * AssetImage component for rendering optimized images from the V2 design system
 * 
 * @example
 * <AssetImage 
 *   name="company-logo" 
 *   alt="Company Logo"
 *   width={200}
 *   height={50}
 * />
 */
const AssetImage: React.FC<AssetImageProps> = ({ 
  name, 
  alt,
  width,
  height,
  className,
  style,
  loading = "lazy",
  ...props 
}) => {
  const getImageSrc = (imageName: typeof name): string => {
    switch (imageName) {
    case 'login-placeholder':
      return ImageMap['login-placeholder'];
    default:
      console.warn(`AssetImage: Unknown image name "${imageName}"`);
      return '';
    }
  };

  const src = getImageSrc(name);
  
  if (!src) {
    return null;
  }

  return (
    <img
      src={src}
      alt={alt}
      width={width}
      height={height}
      className={className}
      style={style}
      loading={loading}
      {...props}
    />
  );
};

export default AssetImage;
