/**
 * AssetImage Types
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-images.cjs
 */

import { GeneratedImageKeys } from './images.generated';

export type ImageName = GeneratedImageKeys;

export interface AssetImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  /**
   * Name of the image (without extension)
   */
  name: ImageName;
  
  /**
   * Alt text for accessibility
   */
  alt: string;
  
  /**
   * Optional width (can be number in pixels or string with units)
   */
  width?: number | string;
  
  /**
   * Optional height (can be number in pixels or string with units)
   */
  height?: number | string;
  
  /**
   * Optional CSS class name
   */
  className?: string;
  
  /**
   * Optional inline styles
   */
  style?: React.CSSProperties;
  
  /**
   * Loading strategy
   * @default "lazy"
   */
  loading?: "lazy" | "eager";
}
