/**
 * Auto-generated image imports
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-images.cjs
 */

import loginPlaceholder from "../../assets-v2/images/login-placeholder.png";

export const ImageMap = {
  "login-placeholder": loginPlaceholder,
} as const;

export type GeneratedImageKeys = "login-placeholder";
