#!/usr/bin/env node

/**
 * Image Component Generator for V2 Design System
 *
 * This script automatically generates React components from PNG/JPEG images
 * in the assets-v2/images directory.
 *
 * Usage: yarn generate:images
 *
 * Generated files:
 * - components-v2/AssetImage/images.generated.ts
 * - components-v2/AssetImage/AssetImage.types.ts
 * - components-v2/AssetImage/AssetImage.tsx
 */

const fs = require("fs");
const path = require("path");

const IMAGES_DIR = path.join(__dirname, "../src/assets-v2/images");
const OUTPUT_DIR = path.join(__dirname, "../src/components-v2/AssetImage");
const INDEX_FILE = path.join(__dirname, "../src/components-v2/index.ts");

/**
 * Get all image files from the images directory
 */
function getImageFiles() {
  if (!fs.existsSync(IMAGES_DIR)) {
    console.error(`❌ Images directory not found: ${IMAGES_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(IMAGES_DIR);
  return files.filter((file) => /\.(png|jpg|jpeg)$/i.test(file));
}

/**
 * Convert filename to camelCase for variable names
 * Example: user-avatar.png -> userAvatar
 */
function toCamelCase(str) {
  return str
    .replace(/\.(png|jpg|jpeg)$/i, "")
    .replace(/-([a-z])/g, (g) => g[1].toUpperCase());
}

/**
 * Convert filename to image name (kebab-case without extension)
 * Example: user-avatar.png -> user-avatar
 */
function toImageName(filename) {
  return filename.replace(/\.(png|jpg|jpeg)$/i, "");
}

/**
 * Generate the images.generated.ts file with import map
 */
function generateImageMapFile(imageFiles) {
  const imports = imageFiles
    .map((file) => {
      const varName = toCamelCase(file);
      return `import ${varName} from '../../../assets-v2/images/${file}';`;
    })
    .join("\n");

  const mapEntries = imageFiles
    .map((file) => {
      const imageName = toImageName(file);
      const varName = toCamelCase(file);
      return `  '${imageName}': ${varName},`;
    })
    .join("\n");

  const imageNames = imageFiles
    .map((file) => `  | '${toImageName(file)}'`)
    .join("\n");

  const content = `/**
 * Auto-generated image imports
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-images.cjs
 */

${imports}

export const ImageMap = {
${mapEntries}
} as const;

export type GeneratedImageKeys =
${imageNames};
`;

  const outputPath = path.join(OUTPUT_DIR, "images.generated.ts");
  fs.writeFileSync(outputPath, content, "utf-8");
  console.log("  ✓ Generated images.generated.ts");
}

/**
 * Generate TypeScript types file
 */
function generateTypesFile(imageFiles) {
  const content = `/**
 * AssetImage Types
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-images.cjs
 */

import { GeneratedImageKeys } from './images.generated';

export type ImageName = GeneratedImageKeys;

export interface AssetImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  /**
   * Name of the image (without extension)
   */
  name: ImageName;
  
  /**
   * Alt text for accessibility
   */
  alt: string;
  
  /**
   * Optional width (can be number in pixels or string with units)
   */
  width?: number | string;
  
  /**
   * Optional height (can be number in pixels or string with units)
   */
  height?: number | string;
  
  /**
   * Optional CSS class name
   */
  className?: string;
  
  /**
   * Optional inline styles
   */
  style?: React.CSSProperties;
  
  /**
   * Loading strategy
   * @default "lazy"
   */
  loading?: "lazy" | "eager";
}
`;

  const outputPath = path.join(OUTPUT_DIR, "AssetImage.types.ts");
  fs.writeFileSync(outputPath, content, "utf-8");
  console.log("  ✓ Generated AssetImage.types.ts");
}

/**
 * Generate the main AssetImage component
 */
function generateComponentFile(imageFiles) {
  const cases = imageFiles
    .map((file) => {
      const imageName = toImageName(file);
      return `    case '${imageName}':
      return ImageMap['${imageName}'];`;
    })
    .join("\n");

  const content = `/**
 * AssetImage Component
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-images.cjs
 */

import React from 'react';
import { ImageMap } from './images.generated';
import { AssetImageProps } from './AssetImage.types';

/**
 * AssetImage component for rendering optimized images from the V2 design system
 * 
 * @example
 * <AssetImage 
 *   name="company-logo" 
 *   alt="Company Logo"
 *   width={200}
 *   height={50}
 * />
 */
const AssetImage: React.FC<AssetImageProps> = ({ 
  name, 
  alt,
  width,
  height,
  className,
  style,
  loading = "lazy",
  ...props 
}) => {
  const getImageSrc = (imageName: typeof name): string => {
    switch (imageName) {
${cases}
    default:
      console.warn(\`AssetImage: Unknown image name "\${imageName}"\`);
      return '';
    }
  };

  const src = getImageSrc(name);
  
  if (!src) {
    return null;
  }

  return (
    <img
      src={src}
      alt={alt}
      width={width}
      height={height}
      className={className}
      style={style}
      loading={loading}
      {...props}
    />
  );
};

export default AssetImage;
`;

  const outputPath = path.join(OUTPUT_DIR, "AssetImage.tsx");
  fs.writeFileSync(outputPath, content, "utf-8");
  console.log("  ✓ Generated AssetImage.tsx");
}

/**
 * Update the main index.ts file to export AssetImage
 */
function updateIndexFile() {
  const currentContent = fs.readFileSync(INDEX_FILE, "utf-8");

  // Check if AssetImage exports already exist
  if (currentContent.includes("AssetImage")) {
    console.log("  ℹ index.ts already includes AssetImage exports");
    return;
  }

  const imageExports = `
// AssetImage exports
export { default as AssetImage } from './AssetImage/AssetImage';
export type { AssetImageProps, ImageName } from './AssetImage/AssetImage.types';
export type { GeneratedImageKeys } from './AssetImage/images.generated';
`;

  const newContent = currentContent.trim() + "\n" + imageExports;
  fs.writeFileSync(INDEX_FILE, newContent, "utf-8");
  console.log("  ✓ Updated index.ts");
}

// Main execution
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

const imageFiles = getImageFiles();

console.log("\n🖼️  Image Component Generator - V2 Design System");
console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");

if (imageFiles.length === 0) {
  console.log("⚠️  No image files found in assets-v2/images/");
  console.log("   Add .png, .jpg, or .jpeg files and run this script again.\n");
  process.exit(0);
}

console.log(
  `📁 Found ${imageFiles.length} image file${
    imageFiles.length > 1 ? "s" : ""
  }:\n`
);

imageFiles.forEach((file, index) => {
  const imageName = toImageName(file);
  const ext = path.extname(file).toUpperCase().slice(1);
  console.log(`  ${index + 1}. ✅ ${file}`);
  console.log(`     ├─ Image Name: "${imageName}"`);
  console.log(`     └─ Format: ${ext}\n`);
});

console.log("🔨 Generating components...\n");

generateTypesFile(imageFiles);
generateImageMapFile(imageFiles);
generateComponentFile(imageFiles);
updateIndexFile();

console.log("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
console.log("✨ Image generation complete!\n");
console.log("📦 Generated files:");
console.log(`   ├─ ${path.join(OUTPUT_DIR, "AssetImage.tsx")}`);
console.log(`   ├─ ${path.join(OUTPUT_DIR, "AssetImage.types.ts")}`);
console.log(`   └─ ${path.join(OUTPUT_DIR, "images.generated.ts")}\n`);
console.log("💡 Usage:");
console.log('   import { AssetImage } from "@/components-v2";\n');
console.log('   <AssetImage name="company-logo" alt="Logo" width={200} />\n');
console.log("📝 Available images:");
imageFiles.forEach((file) => {
  console.log(`   • ${toImageName(file)}`);
});
console.log("");
