export interface Product {
  sku: string
  Name: string
  isActive: boolean
  Description: string
  notes: string
  timesSold: number
  createdBy: string
  modifiedBy: string
  backOrder: string[]
  EachWholesale: number
  WebDescription: string
  PartFamilyId: number
  PartFamilyWebId: string
  PartFamilyName: string
  CategoryId: string
  CategoryWebId: string
  CategoryName: string
  BrandId: string
  BrandWebId: string
  BrandName: string
  NewDate: string
  ImageName: string
  ImageThumb: string
  ImageMedium: string
  ImageFamilyName: string
  ImageFamilyThumb: string
  ImageFamilyMedium: string
  WebUrl: string
  SoldInQuantitiesOf: string
  Looks: number
  Discontinued: number
  Signature: number
  Exclusive: number
  Ium: string
  VolumeUom: string
  WeightUom: string
  StockCodeDen: string
  StockCodeRom: string
  StockCodeIml: string
  StockCodeOlv: string
  StockCodeLaw: string
  StockCodeTra: string
  StockCodeTyl: string
  StockCodeGre: string
  StockCodeMxm: string
  StockCodeLeb: string
  StockCodeStb: string
  StockDen: number
  StockRom: string
  StockIml: string
  StockOlv: string
  StockLaw: string
  StockTra: string
  StockTyl: string
  StockGre: string
  StockMxm: string
  StockLeb: string
  StockStb: string
  StockTotal: number
  NoUps: number
  UlEtl: string
  EpaNum: string
  IsSale: number
  IsNew: number
  IsSecond: number
  EachUpc: string
  EachMsrp: string
  EachPrice: string
  EachVolume: string
  EachDimWeight: string
  EachWeight: string
  EachLength: string
  EachWidth: string
  EachHeight: string
  CaseUpc: string
  CaseQuantity: string
  CaseVolume: string
  CaseDimWeight: string
  CaseWeight: string
  CaseLength: string
  CaseWidth: string
  CaseHeight: string
  PalletUpc: string
  PalletQuantity: string
  PalletVolume: string
  PalletDimWeight: string
  PalletWeight: string
  PalletLength: string
  PalletWidth: string
  PalletHeight: string
  Warranty: string
  Hazmat: number
  Prop65: number
  LegacyPartId: string
}
